version: '3.8'

services:
  necocelotgateway:
    container_name: nec-ocelot-gateway
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+:5000

networks:
  default:
      name: srvnecmettin